//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSUrban.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inmuebles
    {
        public string Expediente { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string Localidad { get; set; }
        public string Vendedor_Arrendador { get; set; }
        public string Comprador_Arrendatario { get; set; }
        public int TipoInmueble { get; set; }
        public string Direccion { get; set; }
        public long Id { get; set; }
        public string Descripcion { get; set; }
        public long EstateCounter { get; set; }
    
        public virtual Clientes Clientes { get; set; }
        public virtual Clientes Clientes1 { get; set; }
        public virtual TipoInmuebles TipoInmuebles { get; set; }
    }
}
