//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSUrbanModelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inmuebles
    {
        public long Id { get; set; }
        public string Expediente { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string Localidad { get; set; }
        public string Descripcion { get; set; }
        public string Direccion { get; set; }
        public string Vendedor_Arrendador { get; set; }
        public string Comprador_Arrendatario { get; set; }
        public int TipoInmueble { get; set; }
        public long EstateCounter { get; set; }
    
        public virtual Clientes Clientes { get; set; }
        public virtual TipoInmuebles TipoInmuebles { get; set; }
    }
}
