//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSUrbanModelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoInmuebles
    {
        public TipoInmuebles()
        {
            this.Inmuebles = new HashSet<Inmuebles>();
        }
    
        public int Id { get; set; }
        public string Description { get; set; }
        public long Counter { get; set; }
    
        public virtual ICollection<Inmuebles> Inmuebles { get; set; }
    }
}
